name: Github iQIYI-DailyBonus

on:
  push:
    branches:
      - master
  schedule:
    - cron: '35 2 * * *'
  workflow_dispatch: {}  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Run iQIYI script
        run: node iQIYI.js
        env:
          iQIYI_COOKIE: ${{ secrets.iQIYI_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
